### ISSUE TITLE
Warning when running the server example

### ISSUE THREAD

**Issue by lucifercr07** [fstab/http2-examples#4]
Facing this warn error when running server examples:
`2018-12-18 00:59:16.605:WARN:oejut.QueuedThreadPool:qtp1531448569-11: 
java.lang.NoSuchFieldError: state
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:211)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:613)
	at org.eclipse.jetty.server.NegotiatingServerConnection.fill(NegotiatingServerConnection.java:153)
	at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:98)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
2018-12-18 00:59:16.607:WARN:oejut.QueuedThreadPool:qtp1531448569-11: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@7b9088f9 in qtp1531448569{STARTED,8<=8<=200,i=3,q=0}
`

**Comment by 15520529** [comment]
Hi @lucifercr07 , choose AlPN version corresponding with your JDK version.
https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html

**Comment by KevinGit585** [comment]
@15520529  thanks for your information. 
https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions
